### ISSUE TITLE
Link the other paper?

### ISSUE THREAD

**Issue by Expertium** [joshdavham/jreadability#5]
https://researchmap.jp/jhlee/published_papers/21426109
This one is more in-depth, so I think it makes sense to link it instead

**Comment by joshdavham** [comment]
I actually did previously link to that one, but that paper actually uses a different formula which led to big discrepencies between this package's model and the model on jreadability.net.

The paper you linked to measures proportion of aux. verbs while the new one measures percentage of particles.
![Fullscreen_2024-10-07__10_33 PM](https://github.com/user-attachments/assets/ce3eb21f-ec29-40b1-bb40-202209c7f989)

With that being said, though, yeah, I'll link that paper again.

**Comment by joshdavham** [comment]
Okay, just re added a link to the original paper in the README 👍
